A Fórmula Mágica é um modelo de fator que classifica as ações por dois fatores:

1. O valor de uma empresa em relação aos seus lucros determina quão “barato” é o preço de mercado de uma ação. Greenblatt define “Barato” como o valor de uma empresa em relação aos seus lucros. Na maioria das vezes, podemos ver isto representado pelo P/L, Greenblatt prefere olhar para EV/EBIT. Isto permite que empresas com diferentes estruturas de endividamento e impostos sejam comparadas mais facilmente. O EV/EBIT compara o Valor da Empresa (Enterprise Value, EV = Capitalização de mercado + Dívida total - Caixa e equivalentes de caixa) ao seu Lucro Antes de Juros e Impostos (Earnings Before Interest and Taxes, EBIT), o EV leva em conta o valor de mercado total da empresa, adicionando as dívidas e subtraindo o caixa, oferecendo assim, uma visão mais abrangente do valor da empresa do que simplesmente seu valor de mercado. O EBIT é uma medida da capacidade de geração de lucro operacional da empresa, excluindo os efeitos das decisões de estrutura de capital e impostos. Um EV/EBIT menor sugere que o preço da ação da empresa pode estar baixo em comparação com a quantidade de lucro operacional que está gerando, indicando que a empresa está subavaliada pelo mercado. No entanto, é importante analisar o EV/EBIT dentro do contexto de cada setor, já que diferentes indústrias têm padrões de avaliação distintos.

2. O retorno sobre o capital determina o quão “boa” é uma empresa. “Bom” é representado pelo ROIC, Greenblatt quantifica a quantidade de capital tangível necessária para operar um negócio e quanto dinheiro cada unidade de capital aplicado irá render. O ROIC é um dos indicadores financeiros mais importantes para analisar a eficiência operacional de uma empresa. Para calcular o ROIC, divide-se o lucro operacional líquido de impostos pelo capital investido total, que inclui dívidas e patrimônio líquido. Um ROIC alto é geralmente interpretado como um sinal de que a empresa está utilizando seu capital de maneira eficaz para gerar lucros.

ROIC utilizada por Greenblatt é diferente da fórmula tradicional

ROIC = EBIT / (Capital Circulante Líquido + Ativos Fixos Líquidos)

Onde o Capital circulante Líquido é um proxy do Capital de Giro da Empresa (Ativo Circulante – Passivo Circulante), os Ativos Fixos Líquidos é proxy dos ativos permanentes (imobilizado e intangíveis, utilizados para gerar retorno no longo prazo. A Taxa de Retorno de Lucros para uma empresa é a fórmula tradicional: Taxa de Retorno = Lucro Operacional / Valor da Empresa

Estes dois indicadores são colocados cada um em um ranking, da melhor (rank 1) para a pior empresa. Depois somamos os números das duas colunas, quanto menor a soma, melhor.

Para os princípios de Greenblatt, empresas pertencentes aos setores de utilidades públicas, bancos e  seguradoras devem ser excluídas da seleção.

In [34]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import requests
from IPython.display import display, HTML


def pct_to_float(number):
    """Convert string to float, remove % char and set decimal point to '.'."""
    return float(number.strip("%").replace(".", "").replace(",", "."))


def b_print(df , n=30 , clean=True):
    
    # from IPython.display import display, HTML

    if clean : # remove tickers da mesma empresa, deixando a primeria ocorrencia
        df['prefixo'] = df['Papel'].astype(str).str[:4]
        df=df.drop_duplicates(subset='prefixo', keep='first')
        # df=df.drop('prefixo', axis=1) 
    
    display(HTML(df.head(n).to_html(index=False)))
    df = None

def setor(setor:int):

    url = f'http://www.fundamentus.com.br/resultado.php?setor={setor}'
    hdr = {'User-agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201' ,
           'Accept': 'text/html, text/plain, text/css, text/sgml, */*;q=0.01' ,
           'Accept-Encoding': 'gzip, deflate' ,
           }
    content = requests.get(url, headers=hdr)
    df = pd.read_html(content.text, decimal=",", thousands='.')[0]
    return list(df['Papel'])

dados do site https://www.fundamentus.com.br/resultado.php

In [39]:
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}
url = 'https://www.fundamentus.com.br/resultado.php'
#junta com a requests
r = requests.get(url, headers=header)
# read_html do pandas põe a tabela num dataframe
funda = pd.read_html(r.text, index_col="Papel",
                     decimal=',', thousands='.',encoding='ISO-8859-1', 
                     converters={'ROE': pct_to_float,
                                 'ROIC': pct_to_float,
                                 'Div.Yield':pct_to_float,
                                 'Mrg Ebit':pct_to_float,
                                 'Mrg. Líq.':pct_to_float,
                                 'Cresc. Rec.5a':pct_to_float,
                                 },
)[0]

In [40]:

data_funds = pd.DataFrame(funda)
data_funds.columns

Index(['Cotação', 'P/L', 'P/VP', 'PSR', 'Div.Yield', 'P/Ativo', 'P/Cap.Giro',
       'P/EBIT', 'P/Ativ Circ.Liq', 'EV/EBIT', 'EV/EBITDA', 'Mrg Ebit',
       'Mrg. Líq.', 'Liq. Corr.', 'ROIC', 'ROE', 'Liq.2meses', 'Patrim. Líq',
       'Dív.Brut/ Patrim.', 'Cresc. Rec.5a'],
      dtype='object')

In [36]:
earning_yield = 'EV/EBIT'  #Quanto menor melhor
return_on_capital = 'ROIC' #ROIC – Quanto maior melhor

### filtros e ranking

- Empresa precisa ter ROIC positivo
- Empresa precisa ter Lucro Operacional positivo.
- Volume de negociação diário medio maior que R$ 1000000.000,00 nos últimos 2 meses.

ROIC – Quanto maior melhor

EV/EBIT – Quanto menor melhor

In [37]:
funds = data_funds.copy()

funds =  funds[funds[earning_yield] > 0]
funds =  funds[funds[return_on_capital] > 0]
funds =  funds[funds['Liq.2meses'] > 1000000]     #Volume diário médio negociado nos últimos 2 meses

""" magic formula rank."""
funds["Rank_earnings_yield"]   = funds[earning_yield].rank(ascending=True, method="min")
funds["Rank_return_on_capital"]= funds[return_on_capital].rank(ascending=False, method="min")
funds["Rank_Final"] = (funds["Rank_earnings_yield"] + funds["Rank_return_on_capital"])
funds.sort_values(by="Rank_Final", ascending=True, inplace=True)
funds.reset_index(inplace=True)
funds.index = funds.index + 1

### lista ranqueada

In [21]:
funds.columns

Index(['Papel', 'Cotação', 'P/L', 'P/VP', 'PSR', 'Div.Yield', 'P/Ativo',
       'P/Cap.Giro', 'P/EBIT', 'P/Ativ Circ.Liq', 'EV/EBIT', 'EV/EBITDA',
       'Mrg Ebit', 'Mrg. Líq.', 'Liq. Corr.', 'ROIC', 'ROE', 'Liq.2meses',
       'Patrim. Líq', 'Dív.Brut/ Patrim.', 'Cresc. Rec.5a',
       'Rank_earnings_yield', 'Rank_return_on_capital', 'Rank_Final'],
      dtype='object')

In [22]:
funds[['Papel','EV/EBITDA', 'ROIC', 'Liq.2meses','Rank_earnings_yield', 'Rank_return_on_capital', 'Rank_Final']].head(20)

,Papel,EV/EBITDA,ROIC,Liq.2meses,Rank_earnings_yield,Rank_return_on_capital,Rank_Final
1,PSSA3,0.59,77.44,1.051250e+08,1.0,1.0,2.0
2,WIZC3,1.81,36.56,5.525580e+06,3.0,5.0,8.0
3,PLPL3,3.22,35.55,3.757180e+07,6.0,7.0,13.0
4,QUAL3,1.63,21.55,1.083450e+07,4.0,14.0,18.0
5,LREN3,2.73,22.79,2.341290e+08,8.0,13.0,21.0
6,ASAI3,3.03,19.52,1.268230e+08,10.0,20.0,30.0
7,CMIN3,4.19,23.02,5.183700e+07,22.0,12.0,34.0
8,BEEF3,3.61,17.90,8.593150e+07,15.0,21.0,36.0
9,VTRU3,3.42,15.67,8.706000e+06,11.0,29.0,40.0
10,LEVE3,5.52,35.92,1.246900e+07,37.0,6.0,43.0
11,PETR4,3.39,17.43,2.326170e+09,19.0,24.0,43.0
12,SEER3,3.11,16.03,1.413490e+07,16.0,28.0,44.0
13,PETR3,3.61,17.43,7.029370e+08,21.0,24.0,45.0
14,CEAB3,2.78,14.72,1.136180e+08,9.0,37.0,46.0
15,CSED3,3.05,15.21,3.351470e+06,12.0,34.0,46.0
16,POMO3,5.59,20.62,4.863220e+06,35.0,15.0,50.0
17,VALE3,4.89,17.62,2.165030e+09,32.0,23.0,55.0
18,POMO4,5.83,20.62,7.617880e+07,41.0,15.0,56.0
19,PCAR3,1.14,12.17,3.806690e+07,2.0,55.0,57.0
20,VLID3,3.74,14.64,5.448310e+06,20.0,39.0,59.0

retira banco, seguradora, utilidade publica (agua e luz - [util-b3](https://www.b3.com.br/pt_br/market-data-e-indices/indices/indices-de-segmentos-e-setoriais/indice-utilidade-publica-util-composicao-da-carteira.htm))

In [23]:
bancos = setor(20)
print(*bancos)
seguros = setor(31)
print(*seguros)
util_agua = setor(2)
util_luz = setor(14)
util=util_agua+util_luz
print(*util)

BSLI4 BSLI3 BNBR3 BAZA3 BRSR6 BRSR3 BRSR5 BGIP4 BMGB4 RPAD3 RPAD6 ABCB4 RPAD5 PINE3 BBDC3 BBAS3 SANB3 BEES3 BEES4 PINE4 SANB11 SANB4 BBDC4 BMIN4 BGIP3 ITSA4 ITSA3 BMIN3 ITUB3 ITUB4 BMEB3 BPAC5 BRBI11 BMEB4 BPAC11 BPAC3 MERC4
IRBR3 WIZC3 BBSE3 PSSA3 CXSE3
AMBP3 SAPR4 SAPR11 SAPR3 SBSP3 CSMG3 ORVR3 CBEE3 AURE3 RIOS3 RNEW3 RNEW4 CEED3 GEPA4 GEPA3 GPAR3 EQPA3 EQPA5 EMAE4 CEEB5 CEEB3 CLSC3 COCE5 EQMA3B CMIG4 CLSC4 EKTR4 ISAE4 NEOE3 COCE3 ALUP4 TAEE3 ISAE3 LIGT3 TAEE11 TAEE4 ALUP11 CMIG3 CPFE3 EKTR3 ALUP3 ENGI4 CEBR5 ENGI11 CEBR6 ENMT3 ENMT4 CEBR3 REDE3 ENGI3 EGIE3 CPLE3 AFLT3 AXIA3 AXIA6 EQTL3 ENEV3

#### sem bancos

In [24]:
# funds = funds[(~funds['Papel'].isin(bancos))&(~funds['Papel'].isin(seguros))&(~funds['Papel'].isin(util))]
b_print(
    funds[~funds['Papel'].isin(bancos)],10
)

#### sem seguradora

In [25]:
# funds = funds[(~funds['Papel'].isin(bancos))&(~funds['Papel'].isin(seguros))&(~funds['Papel'].isin(util))]
b_print(
    funds[~funds['Papel'].isin(seguros)],10
)

#### sem utilidade publica

In [26]:
# funds = funds[(~funds['Papel'].isin(bancos))&(~funds['Papel'].isin(seguros))&(~funds['Papel'].isin(util))]
b_print(
    funds[~funds['Papel'].isin(util)],10
)

#### sem as 3 classes

In [27]:
b_print(
    funds[(~funds['Papel'].isin(bancos))&(~funds['Papel'].isin(seguros))&(~funds['Papel'].isin(util))],
    10
)

outros filtros

In [28]:
funds2 =  funds[funds['P/L'] > 0]                # sem prejuizo atual
funds2 =  funds2[(funds['P/L'] < 30)]           # não estar excessivamente cara
funds2 =  funds2[funds['Dív.Brut/ Patrim.'] < 3.5]  # endividamento sob controle
funds2 =  funds2[funds['Cresc. Rec.5a'] > 0]    # crescimento nos ultimos 5 anos

In [29]:
b_print(
    funds2[(~funds2['Papel'].isin(bancos))&(~funds2['Papel'].isin(seguros))&(~funds2['Papel'].isin(util))],
    10
)

retirar BDR

In [30]:
# Padrão a ser buscado XYZW3[2,3,4,5]
padrao = r'[A-Z]{4}3[2-5]'

# Filtrando as linhas onde o padrão ocorre na coluna 'Papel'
funds[funds['Papel'].str.contains(padrao)]

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a,Rank_earnings_yield,Rank_return_on_capital,Rank_Final
58,AURA33,152.36,-72.05,22.63,6.473,0.81,3.738,-436.83,12.35,-7.24,...,0.97,42.98,-31.41,151761000.0,1.462190e+09,1.55,21.82,131.0,3.0,134.0

A fórmula:
1. Estabeleça uma capitalização de mercado mínima.
2. Exclua ações de serviços públicos e financeiras  (ou seja, fundos mútuos, bancos e companhias de seguros).
3. Excluir empresas estrangeiras (ADRs)
4. Determine o rendimento dos lucros da empresa = EBIT/EV
5. Determine o retorno sobre o capital da empresa = EBIT/ (Ativo Fixo Líquido + Capital de Giro).
6. Classifique todas as empresas acima da capitalização de mercado escolhida pelo maior rendimento de lucros e maior retorno sobre o capital (classificado como porcentagens)
7. Invista em 20 a 30 empresas com melhor classificação, acumulando 2 a 3 posições por mês durante um período de 12 meses
8. Reequilibre o portfólio uma vez por ano, vendendo os perdedores uma semana antes do ano e os vencedores uma semana depois do ano.
9. Continuar por um período de longo prazo (5 a 10+ anos)

https://en.wikipedia.org/wiki/Magic_formula_investing

O retorno sobre o capital de Greenblatt difere de um valor típico de ROE ou ROIC. Dentro da Fórmula Mágica, o retorno sobre o capital de uma empresa é medido como EBIT/capital tangível empregado. Em outras palavras, estamos tentando encontrar os custos tangíveis para o negócio na geração dos lucros reportados dentro do período, onde o capital tangível empregado é definido mais precisamente como Capital Circulante Líquido mais Ativos Fixos Líquidos.

O capital de giro líquido é simplesmente o total do ativo circulante menos o passivo circulante, com um ajuste para remover dívidas com juros de curto prazo do passivo circulante e outro para remover o excesso de caixa. Greenblatt não oferece detalhes sobre como o excesso de caixa deve ser considerado, mas muitas vezes é calculado com base em uma porcentagem do caixa necessário em relação às vendas geradas em um período.

In [41]:
data_funds.loc['INEP4']

Cotação              1.560000e+00
P/L                 -1.700000e-01
P/VP                -5.000000e-02
PSR                  1.421800e+01
Div.Yield            0.000000e+00
P/Ativo              1.880000e-01
P/Cap.Giro          -1.000000e-01
P/EBIT              -8.000000e-01
P/Ativ Circ.Liq     -4.000000e-02
EV/EBIT             -9.390000e+00
EV/EBITDA           -1.017000e+01
Mrg Ebit            -1.769240e+03
Mrg. Líq.           -8.435340e+03
Liq. Corr.           1.400000e-01
ROIC                -2.656000e+01
ROE                  2.827000e+01
Liq.2meses           4.399890e+04
Patrim. Líq         -1.567110e+09
Dív.Brut/ Patrim.   -5.200000e-01
Cresc. Rec.5a       -2.306000e+01
Name: INEP4, dtype: float64

==================================================================================================

In [47]:
# ============================================================
# MAGIC FORMULA 
# ============================================================

df_mf = df_score = data_funds.copy()

# Converter para numérico
cols = ['EV/EBIT', 'ROIC', 'Liq.2meses']
for c in cols:
    df_mf[c] = pd.to_numeric(df_mf[c], errors='coerce')

# Filtros básicos (Brasil)
df_mf = df_mf[
    (df_mf['EV/EBIT'] > 0) &
    (df_mf['ROIC'] > 0) &
    (df_mf['Liq.2meses'] > 1_000_000)
]

# Earnings Yield implícito
df_mf['earnings_yield'] = 1 / df_mf['EV/EBIT']

# Rankings (Greenblatt)
df_mf['rank_ey'] = df_mf['earnings_yield'].rank(ascending=False)
df_mf['rank_roic'] = df_mf['ROIC'].rank(ascending=False)

df_mf['magic_score'] = df_mf['rank_ey'] + df_mf['rank_roic']

df_magic = df_mf.sort_values('magic_score')

carteira = (
    df_magic
    .loc[:, [
        # 'Papel',
        'EV/EBIT',
        'ROIC',
        'earnings_yield',
        'magic_score',
        'Liq.2meses'
    ]]
)

carteira.head(15)

       EV/EBIT   ROIC  earnings_yield  magic_score    Liq.2meses
Papel
PSSA3     0.60  77.44        1.666667          2.0  1.051250e+08
WIZC3     2.09  36.56        0.478469          8.0  5.525580e+06
PLPL3     3.30  35.55        0.303030         13.0  3.757180e+07
QUAL3     2.46  21.55        0.406504         18.0  1.083450e+07
LREN3     3.70  22.79        0.270270         21.0  2.341290e+08
ASAI3     3.95  19.52        0.253165         30.0  1.268230e+08
CMIN3     5.22  23.02        0.191571         34.0  5.183700e+07
BEEF3     4.54  17.90        0.220264         36.0  8.593150e+07
VTRU3     4.37  15.67        0.228833         40.0  8.706000e+06
LEVE3     6.29  35.92        0.158983         43.0  1.246900e+07
PETR4     4.84  17.43        0.206612         43.5  2.326170e+09
SEER3     4.56  16.03        0.219298         44.0  1.413490e+07
PETR3     5.16  17.43        0.193798         45.5  7.029370e+08
CSED3     4.46  15.21        0.224215         46.0  3.351470e+06
CEAB3     3.77  14.72        0.265252         46.5  1.136180e+08

In [49]:

cols_num = [
    'EV/EBIT', 'P/L', 'P/VP',
    'ROIC', 'Mrg Ebit', 'ROE',
    'Cresc. Rec.5a', 'Liq.2meses'
]

for c in cols_num:
    df_score[c] = pd.to_numeric(df_score[c], errors='coerce')

# Filtros mínimos
df_score = df_score[
    (df_score['EV/EBIT'] > 0) &
    (df_score['P/L'] > 0) &
    (df_score['ROIC'] > 0) &
    (df_score['Liq.2meses'] > 1_000_000)
]

# Value score
df_score['rank_ev_ebit'] = df_score['EV/EBIT'].rank(ascending=True)
df_score['rank_pl'] = df_score['P/L'].rank(ascending=True)
df_score['rank_pvp'] = df_score['P/VP'].rank(ascending=True)

df_score['value_score'] = (
    df_score['rank_ev_ebit'] +
    df_score['rank_pl'] +
    df_score['rank_pvp']
)

# Quality score
df_score['rank_roic'] = df_score['ROIC'].rank(ascending=False)
df_score['rank_mrg'] = df_score['Mrg Ebit'].rank(ascending=False)
df_score['rank_roe'] = df_score['ROE'].rank(ascending=False)

df_score['quality_score'] = (
    df_score['rank_roic'] +
    df_score['rank_mrg'] +
    df_score['rank_roe']
)

# growth score
df_score['rank_growth'] = df_score['Cresc. Rec.5a'].rank(ascending=False)

df_score['growth_score'] = df_score['rank_growth']

# Score final (pesos claros)
# Sugestão equilibrada para position trade:
# Value: 40%
# Quality: 40%
# Growth: 20%

# Normalizar scores (0–1)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_score[['value_n', 'quality_n', 'growth_n']] = scaler.fit_transform(
    df_score[['value_score', 'quality_score', 'growth_score']]
)

# Score final (quanto MENOR, melhor)
df_score['final_score'] = (
    0.4 * df_score['value_n'] +
    0.4 * df_score['quality_n'] +
    0.2 * df_score['growth_n']
)

df_final = df_score.sort_values('final_score')
carteira = (
    df_final
    .loc[:, [
        # 'Papel',
        'EV/EBIT',
        'P/L',
        'P/VP',
        'ROIC',
        'Mrg Ebit',
        'ROE',
        'Cresc. Rec.5a',
        'final_score',
        'Liq.2meses'
    ]]
)

carteira.head(15)

,EV/EBIT,P/L,P/VP,ROIC,Mrg Ebit,ROE,Cresc. Rec.5a,final_score,Liq.2meses
Papel,,,,,,,,,
VTRU3,4.37,5.30,0.67,15.67,36.14,12.64,18.60,0.166976,8.706000e+06
JHSF3,4.50,3.59,1.01,12.29,46.84,28.10,9.77,0.178911,3.725640e+07
PLPL3,3.30,7.68,2.72,35.55,25.46,35.38,27.73,0.192482,3.757180e+07
WIZC3,2.09,7.32,2.11,36.56,50.36,28.82,14.28,0.193654,5.525580e+06
PSSA3,0.60,9.67,2.08,77.44,82.26,21.48,16.78,0.205679,1.051250e+08
POMO3,6.20,6.02,1.92,20.62,15.72,31.92,26.67,0.214758,4.863220e+06
ECOR3,6.87,7.22,1.56,12.83,35.34,21.59,25.88,0.221542,8.870650e+07
POMO4,6.47,6.33,2.02,20.62,15.72,31.92,26.67,0.231716,7.617880e+07
RECV3,7.04,6.30,0.93,11.53,24.75,14.74,26.02,0.249075,5.736580e+07
CSED3,4.46,6.82,1.27,15.21,20.40,18.66,11.88,0.268940,3.351470e+06
LAVV3,8.27,6.76,1.87,11.11,21.98,27.65,37.02,0.273288,1.450290e+07
MILS3,6.96,10.78,2.06,19.70,35.35,19.11,24.49,0.281478,1.354040e+07
PETR4,4.84,5.64,1.49,17.43,39.64,26.49,-0.78,0.283679,2.326170e+09
CURY3,7.65,11.40,8.05,39.40,26.16,70.60,32.58,0.285208,1.242110e+08
GMAT3,5.39,5.78,1.02,11.93,5.63,17.65,24.06,0.293966,6.341170e+07

Interpretação correta
Score menor = melhor

Value garante margem de segurança

Quality reduz value trap

Growth evita empresas “baratas que não crescem”

==================================================================================================