Carteira baseada no número de Graham sobre o valor intrínseco de uma ação, foca em pegar empresas que sejam lucrativas e baratas: empresas operando a P/L menor que 15 e com P/VPA menor que 1,5. Multiplicando 15 x 1,5 temos o número 22,5 que nos indica a fórmula de graham. Valor Intrínseco de uma ação = $\sqrt{22,5 \times \text{LPA} \times \text{VPA}}$.

Critérios:


- Ter Lucro por ação maior que zero ,isto é, a empresa não pode estar com prejuízo atualmente
- Ter Valor Patrimonial por ação positivo, ou seja, a empresa não pode ter mais passivos (obrigações a pagar) que ativos (bens ou direitos a receber)
- Ter volume médio de negociação diário de no mínimo R$250.000,00
- Ter lucro líquido medio positivo em todos os últimos 5 exercícios.

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
from IPython.display import display, HTML

def b_print(df , n=30 , clean=True): #beauty print :)
    
    # from IPython.display import display, HTML

    # if clean : # remove tickers da mesma empresa, deixando a primeria ocorrencia
    #     df['prefixo'] = df['Papel'].astype(str).str[:4]
    #     df=df.drop_duplicates(subset='prefixo', keep='first')
    #     # df=df.drop('prefixo', axis=1) 
    
    display(HTML(df.head(n).to_html(index=False)))
    df = None

In [2]:

# atualiza info fundamentlista

from DT_atualiza_settings import *
from DT_StatusInvest import SI
SI(mercado = 'Acoes' )

 ====== SI Acoes =====
 ====== Busca
 ====== Download

In [2]:

#carrega a info fundamentalista num dataframe

import os
# Caminho do arquivo local
file_path = os.path.expanduser('~/GHub/Finance-playground/data/SI_Acoes.csv')
# URL para o arquivo online
file_url = 'https://raw.githubusercontent.com/BDonadelli/Finance-playground/refs/heads/main/data/SI_Acoes.csv'

# Verificar se o arquivo existe localmente
if os.path.exists(file_path):
    # Ler o arquivo local
    dados = pd.read_csv(file_path,sep=';' , decimal=',' ,thousands ='.' )
    print("Arquivo lido localmente.")
else:
    # Ler o arquivo a partir da URL
    dados = pd.read_csv(file_url,sep=';' , decimal=',' ,thousands ='.' )
    print("Arquivo lido da URL, pode não estar autalizado.")

Arquivo lido localmente.

In [4]:
dados.columns

Index(['TICKER', 'PRECO', 'DY', 'P/L', 'P/VP', 'P/ATIVOS', 'MARGEM BRUTA',
       'MARGEM EBIT', 'MARG. LIQUIDA', 'P/EBIT', 'EV/EBIT',
       'DIVIDA LIQUIDA / EBIT', 'DIV. LIQ. / PATRI.', 'PSR', 'P/CAP. GIRO',
       'P. AT CIR. LIQ.', 'LIQ. CORRENTE', 'ROE', 'ROA', 'ROIC',
       'PATRIMONIO / ATIVOS', 'PASSIVOS / ATIVOS', 'GIRO ATIVOS',
       'CAGR RECEITAS 5 ANOS', 'CAGR LUCROS 5 ANOS', ' LIQUIDEZ MEDIA DIARIA',
       ' VPA', ' LPA', ' PEG Ratio', ' VALOR DE MERCADO'],
      dtype='object')

In [5]:
cols = [
    'TICKER', 'PRECO',
    'valor intrinseco', 'Delta (%)',
    'CAGR LUCROS 5 ANOS',
    'P/L', 'P/VP',
    'ROE', 'DIVIDA LIQUIDA / EBIT',
]

In [6]:
# criterios basicos de seleção

criterios = (
        (dados[' LIQUIDEZ MEDIA DIARIA'] > 300000) &
        (dados[' LPA'] > 0) & 
        (dados[' VPA'] > 0) & 
        (dados['CAGR LUCROS 5 ANOS'] > 0)
)

# criterios com filtros extras de qualidade

criterios_extras = (
    (criterios) & 
    (dados['ROE'] > 0.08) &
    (dados['DIVIDA LIQUIDA / EBIT'] < 4)
)

# 'DIVIDA LIQUIDA / EBIT' é NaN para bancos

bancos = [
    "ABCB4",
    "BAZA3", "BBAS3", "BBDC3", "BBDC4", "BEES3", "BEES4", "BGIP3", "BGIP4",
    "BGIP4", "BMEB3", "BMEB4", "BMGB4", "BNBR3", "BPAC11", "BPAC3", "BPAC5", "BPAN11", "BPAN4", "BPAR3",
    "BPAT33", "BRSR3", "BRSR5", "BRSR6", "BSLI3", "BSLI4", "BSLI4", "BRIV3", "BRIV4", "BMIN3", "BMIN4"
    "IRBR3", "ITUB3", "ITUB4", 
    "MERC3", "MERC4", "MODL3",  "MODL4", "MODL11",  "PINE3","PINE4", "SANB11", "SANB3","SANB4",
    "BBSE3", "CRIV3", "CRIV4", "CSAB3", "CSAB4", "FIGE3", "FIGE4", "FIGE3", "FNCN3", "IDVL3", "IDVL4" , "IRBR3",
    "BMIN3" , "BMIN4", "BIDI3", "BIDI4", "BIDI11", 
    ]

# Substitui por 0 quando o ticker for de banco
dados.loc[dados["TICKER"].isin(bancos),    "DIVIDA LIQUIDA / EBIT"] = 0

In [7]:

# retira linha de ticker que não são mais negociados

delisted = [
    'SOMA3','JBSS3','OIBR3'
]
dados = dados[~dados['TICKER'].isin(delisted)]

In [8]:
# valor intrinseco da acao
dados['valor intrinseco'] = np.round(np.sqrt(22.5 * dados[' LPA'] * dados[' VPA']),2)
# potencial de crescimento 
dados['Delta (%)'] = np.round((dados['valor intrinseco'] / dados['PRECO'] -1)*100,2)
'''
rank() atribui uma posição relativa a cada valor da série. O menor valor recebe rank 1 (ascending=True)
Todos os valores empatados recebem o menor rank possível dentro do empate (method="min")
'''
dados["Rank"] = dados['Delta (%)'].rank(ascending=True, method="min")
# ordena por rank em ordem decrescente
dados.sort_values(by="Rank", ascending=False, inplace=True)

# ajeitando uns numeros

dados['VAL DE MERCADO (em Bilhoes)'] = dados[' VALOR DE MERCADO']  / 1e9
dados['LIQ MEDIA DIARIA (em Milhoes)'] = dados[' LIQUIDEZ MEDIA DIARIA'] / 1e6

In [9]:
b_print(dados.loc[criterios, cols],n=10)

In [10]:
b_print(dados.loc[criterios_extras, cols],n=10)

In [11]:

# # remove empresas repetidas, mantem primeira ocorrencia

# dados['prefixo'] = dados['TICKER'].str[:4]
# # dados.drop_duplicates(subset='prefixo', keep='first')
# dados_limpo = dados.drop_duplicates(subset='prefixo', keep='first')
# # df_limpo = df_limpo.drop('prefixo', axis=1) 
# b_print(dados_limpo[colunas_exibidas])

In [12]:

# Filtro de valor (Graham + margem)
value_filter = dados['Delta (%)'] >= 25
# Catalisador de valuation — P/L deprimido
catalyst_pl = dados['P/L'] < 12
# Catalisador patrimonial — P/VPA baixo
catalyst_pvp = dados['P/VP'] < 1.2
# Pelo menos 1 catalisador ativo
dados['Catalisador'] = (
    catalyst_pl |
    catalyst_pvp
)

# Screening final 

screening = dados[
    criterios_extras &
    value_filter &
    dados['Catalisador']
].copy()
# Score de position trade (simples e robusto)
screening['Score'] = (
    (screening['Delta (%)'] / 100) * 0.5 +
    (screening['CAGR LUCROS 5 ANOS'].clip(0, 20) / 100) * 0.3 +
    ((12 - screening['P/L']).clip(0, 12) / 12) * 0.2
)
#  Ordenação final
screening.sort_values('Score', ascending=False, inplace=True)
# screening.reset_index(drop=True, inplace=True)
# screening.index = screening.index + 1


cols = [
    'TICKER', 'PRECO',
    'valor intrinseco', 'Delta (%)',
    'CAGR LUCROS 5 ANOS',
    'P/L', 'P/VP',
    'ROE', 'DIVIDA LIQUIDA / EBIT',
    'Score'
]

b_print(screening[cols],n=10)

Interpretação prática (position trade)

Delta alto + Score alto
→ desconto real com gatilho

Score alto, Delta médio
→ re-rating provável

Delta alto, Score baixo
→ possível value trap

In [13]:
pd.options.display.float_format = (
    lambda x: f"{x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
)

carteira = (screening['TICKER'].head(10)+'.SA').to_list()

import yfinance as yf
price = yf.download(
    tickers=carteira,
    period='1d',
    interval='1d',
    group_by='ticker',
    auto_adjust=True,
    progress=False
)

# Extrair preço de fechamento
precos = {}

for t in carteira:
    try:
        precos[t.replace('.SA', '')] = price[t]['Close'].iloc[-1]
    except KeyError:
        precos[t.replace('.SA', '')] = None

precos = pd.DataFrame.from_dict(precos, orient="index", columns=["Close"])


precos

       Close
ALLD3   6,14
EVEN3   5,67
AZZA3  20,06
LOGG3  26,51
CYRE4  19,94
JHSF3  11,29
TRIS3   4,51
SYNE3   3,77
CYRE3  21,85
EMAE4  41,68

In [14]:
# criterios minimos

carteira = (dados.loc[criterios]['TICKER'].head(10)+'.SA').to_list()

price = yf.download(
    tickers=carteira,
    period='1d',
    interval='1d',
    group_by='ticker',
    auto_adjust=True,
    progress=False
)

# Extrair preço de fechamento
precos = {}

for t in carteira:
    try:
        precos[t.replace('.SA', '')] = price[t]['Close'].iloc[-1]
    except KeyError:
        precos[t.replace('.SA', '')] = None

precos = pd.DataFrame.from_dict(precos, orient="index", columns=["Close"])
precos

       Close
ALLD3   6,14
BRSR6  14,93
MTRE3   3,49
EVEN3   5,67
AZZA3  20,06
BAZA3  82,79
COCE5  33,91
MELK3   3,19
LOGG3  26,51
CYRE4  19,94

================================================================================================

### outra estória de porque 22,5

O número 22,5 na Fórmula de Graham é um fator de ponderação que tem um propósito específico. Essa constante foi escolhida por Graham pra ajustar a avaliação do preço justo de uma ação com base na taxa de crescimento anual esperada da empresa.

O número 22,5 é o resultado da multiplicação de 8,5 por 2,65 (8,5 x 2,65 = 22,5). O número 8,5 é a base que Graham considerou razoável pra uma empresa com taxa de crescimento zero, ou seja, uma empresa que não cresce. Já o número 2,65 representa a média do retorno exigido pelos investidores no mercado de ações durante a época de Graham, que era de aproximadamente 4,4% acima da taxa de retorno dos títulos do Tesouro dos Estados Unidos. O fator 22,5 ajuda a ajustar o preço justo com base no crescimento da empresa e na expectativa de retorno dos investidores. Esse ajuste garante que a Fórmula de Graham considere a taxa de crescimento anual esperada e reflita uma avaliação mais realista do preço justo de uma ação.

In [15]:
import pandas as pd
import numpy as np
import requests
from io import StringIO
pd.set_option('display.max_columns', None)


url1 = "https://www.fundamentus.com.br/resultado.php"

header = {
    "User-Agent": "Mozilla/5.0",
    "X-Requested-With": "XMLHttpRequest"
}
#Verificar status HTTP
r1 = requests.get(url1, headers=header, timeout=30)
r1.raise_for_status()

dados = pd.read_html(
    StringIO(r1.text),
    decimal=",",
    thousands="."
)[0]

# limpar colunas
dados.columns = (
    dados.columns
    .str.strip()
    .str.replace(".", "", regex=False)
)

dados['ROE'] = dados['ROE'].str.replace('%', '', regex=False).str.replace(".", "", regex=False).str.replace(',', '.', regex=False).astype('float')
dados['Cresc Rec5a'] = dados['Cresc Rec5a'].str.replace('%', '', regex=False).str.replace(".", "", regex=False).str.replace(',', '.', regex=False).astype('float')
dados.rename(columns={'ROE':'ROE(%)' , 'Cresc Rec5a' : 'Cresc Rec5a(%)'},inplace=True)

# LPA e VPA
dados["LPA"] = np.where(dados["P/L"] > 0, dados["Cotação"] / dados["P/L"], np.nan)
dados["VPA"] = np.where(dados["P/VP"] > 0, dados["Cotação"] / dados["P/VP"], np.nan)

# Graham seguro
graham_base = 22.5 * dados["LPA"] * dados["VPA"]
graham_base = graham_base.where(graham_base > 0)
dados["valor intrinseco"] = np.round(np.sqrt(graham_base), 2)

# Delta
dados["Delta (%)"] = np.round(
    (dados["valor intrinseco"] / dados["Cotação"] - 1) * 100,
    2
)

# ordenar
dados = dados.sort_values("Delta (%)", ascending=False)

# print(dados [['Papel' , 'Cotação' , "Delta (%)" , "valor intrinseco" ]])

criterios = (
        (dados['Liq2meses'] > 1000000) &
        (dados['LPA'] > 0) & 
        (dados['VPA'] > 0) & 
        (dados['Cresc Rec5a(%)'] > 0)& 
        (dados['ROE(%)'] > 8) &
        (dados['Liq Corr'] > 1 )& 
        (dados['DívBrut/ Patrim'] < 1 )
)

KeyError: 'DívBrut/ Patrim'

In [ ]:


print(dados[criterios][ [
    'Papel', 'Cotação',
    'valor intrinseco', 'Delta (%)',
    'P/L', 'P/VP',
    'ROE(%)'
]].head(20) )

      Papel  Cotação  valor intrinseco  Delta (%)  P/L  P/VP  ROE(%)
487   AZZA3    21,90             61,78     182,10 4,96  0,57   11,42
453   RIAA3     9,95             26,62     167,54 3,38  0,93   27,56
499   VTRU3    13,87             33,41     140,88 5,54  0,70   12,64
542   LOGG3    26,31             61,09     132,19 6,52  0,64    9,83
537   MELK3     3,48              7,97     129,02 6,41  0,67   10,53
516   TRIS3     5,00             10,61     112,20 5,95  0,84   14,06
491   CYRE4    22,66             47,08     107,77 5,16  1,01   19,62
518   RECV3    13,10             26,85     104,96 6,02  0,89   14,74
513   CEAB3    11,20             22,72     102,86 5,88  0,93   15,84
530   DEXP3     7,29             14,67     101,23 6,24  0,89   14,34
522   VLID3    19,44             38,75      99,33 6,09  0,93   15,31
509   SAPR4     8,00             15,90      98,75 5,81  0,98   16,84
504   GMAT3     4,55              8,98      97,36 5,72  1,01   17,65
596   PFRM3     7,85             15,35      95,54 8,17  0,72    8,84
519  SAPR11    41,55             79,40      91,10 6,04  1,02   16,84
479   JHSF3    12,98             24,75      90,68 4,69  1,32   28,10
580   EZTC3    14,64             27,65      88,87 7,69  0,82   10,64
503   CYRE3    25,06             47,05      87,75 5,70  1,12   19,62
585   ISAE4    29,21             51,81      77,37 7,86  0,91   11,57
603   VITT3     3,48              6,08      74,71 8,48  0,87   10,32